name: mlops-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - pip-tools=7.3.0
  - pip:
    - -r requirements.txt

# conda env create --file environment.yml
# conda env update --file environment.yml --prune